Fix playtime file corruption if not-a-number
Fixes the following error, which will permanently crash the Tracker on-startup. This fix ensures only real numbers are set to the time tracking variables used for playtime calculations.

NLua.Exceptions.LuaScriptException: ironmon_tracker/Tracker.lua:85: attempt to perform arithmetic on upvalue 'startSeconds' (a nil value)